### ISSUE TITLE
Mugs for openSUSE conference 2019 / merge GSoC mugs to main repo

### ISSUE THREAD

**Issue by TheRealBro** [openSUSE/artwork#31]
@hellcp as asked - here comes the issue.

Could you create a mug based on:

https://github.com/openSUSE/artwork/blob/master/Logo/oSC19%20logo%20with%20name.png

And merge the mug designs from this repo please:

https://github.com/raniaamina/artwork/tree/master/Marketing%20Materials/miscellaneous/GSoC%20Mugs

My favourite colour for a mug (regarding costs and easyness of ordering as well) would be a black mug. So the design should work on a black background. I'm pretty sure it will be hard to impossible getting the "smaller" amount of mugs for oSC19 in the correct openSUSE blue color code, like used in the following example.
https://raw.githubusercontent.com/raniaamina/artwork/master/Marketing%20Materials/miscellaneous/GSoC%20Mugs/mugs_by_rania_1.png

Initial idea comes from @Ana06 and you can see the trello comments about it here:
https://trello.com/c/qlLFoGf7/111-get-prices-on-backpacks-on-tshirts-for-osc19#comment-5be4beeedbf16c0c8cf19b2c

Thanks a bunch in advance =)

**Comment by Ana06** [comment]
@TheRealBro I have already proposed a design: https://raw.githubusercontent.com/raniaamina/artwork/master/Marketing%20Materials/miscellaneous/GSoC%20Mugs/mugs_by_rania_1.png

I asked some designers in openSUSE to help me to come up with some mugs for GSoC. As I couldn't use all of them and all of them were awesome, I though it would be a great idea to use that one for the openSUSE conference. That is what I told @ddemaio some time ago and the idea of the [comment in Trello](https://trello.com/c/qlLFoGf7/111-get-prices-on-backpacks-on-tshirts-for-osc19#comment-5be4beeedbf16c0c8cf19b2c). 

I am sure @hellcp could make a great design as well, but that was not what I proposed. I would appreciate that the person who created the original design is involved in this, instead of just asking someone else, as it may be considered unrespectful.

I don't think that the mug needs to be based on https://github.com/openSUSE/artwork/blob/master/Logo/oSC19%20logo%20with%20name.png and I also wouldn't like it to be black. I liked the one I sent, just removing the part about mentoring.

**Comment by TheRealBro** [comment]
ok. than I close this one again. I hope somebody creates a PR. I hope somebody cares about the design of the mugs. And I hope somebody finds mugs in openSUSE dark blue.

**Comment by Ana06** [comment]
@TheRealBro 

> And I hope somebody finds mugs in openSUSE dark blue.

This is done. @ddemaio already made some research about the colors. It is not possible to have exactly the same one, but something similar. 

> I hope somebody cares about the design of the mugs

We have already a design.
