### ISSUE TITLE
update branding-guidelines regarding format

### ISSUE THREAD

**Issue by TheRealBro** [openSUSE/artwork#33]
I would like to see, if we could add mandantory free formats to our branding guidlines here:

http://opensuse.github.io/branding-guidelines/

I understand, the need of proprietary tooling in the graphics industry, as we should not limit somebody's creativity by forcing them to use free software tools with which they are less productive and more blocked.
But most software tools (like Adobe AI, Adobe PS, CorelDraw, etc.) are able to export .eps or .svg as "free and compatible" formats that others in  the community, who only have Inkscape and want to work with the files can start from there.

That's why I suggest to add free formats as mandatory export for our artwork, next to the Adobe and PNG files, in our artwork repository.

@hellcp @cboltz @Ana06 @sysrich - adding board to maybe take care of this issue =)

**Comment by hellcp** [comment]
I was actually thinking about making this repo svg/gimp source only, and automatically generate another repo with artwork in a format that Doug can use (png/jpg). This repo is way too large and that has to change some way. I agree that AI files probably shouldn't be there, but that's what SUSE sends out.

**Comment by cboltz** [comment]
I doubt you'll need the help of the board here since the answers are quite obvious (do you really expect someone votes against SVG files?), but I'll reply nevertheless ;-)

I really like the idea of having (also) free formats like SVG of everything - and I'm quite sure *everybody* (not only the board) will tell you the same ;-)

I don't have a problem with AI files as long as there's a SVG next to them - actually that's probably better than dropping the original format just for the sake of only publishing files in free formats (and possibly loosing some "internal" information that can't be exported to SVG). Nevertheless I'll be more than happy about each file where SVG is the original format ;-)

Regarding splitting this repo and moving autogenerated PNG and JPG files to another repo: I'm not sure if that makes sense (spreading the content across multiple places can cause confusion), but I'll leave that decision to the artwork team ;-)

**Comment by hellcp** [comment]
@cboltz current state of the repos is way more confusing :P

**Comment by hellcp** [comment]
@simotek Eh, yes and no, .ai contains some additional stuff, but in case like ours where the collaboration should happen between people using non-free and free software, it would make more sense to use standardized format that is supported by all of them.

**Comment by hellcp** [comment]
The info was forwarded to SUSE, from now on the policy is to use open formats only.
